web:
  image: cdams/php-couchbase
  #build: .
  mem_limit: 2000m
  ports:
    - "80:80"
  volumes:
    - .:/app
  links:
    - couchbase:db
    - couchbase_volumetrie:dbVol
couchbase:
  image: couchbase
  ports:
    - "8091:8091"
    - "8092:8092"
    - "8093:8093"
  volumes:
    - /var/lib/boot2docker/couchbase-catalogue:/opt/couchbase/var
couchbase_volumetrie:
  image: couchbase
  ports:
    - "9091:8091"
    - "9092:8092"
    - "9093:8093"
  volumes:
    - /var/lib/boot2docker/couchbase-catalogue-volumetrie:/opt/couchbase/var
